/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package orderreceiverdemo;

import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import java.io.*;

/**
 *
 * @author Disc2
 *////////
public class MainFrame extends javax.swing.JFrame {

        /**
         * Creates new form MainFrame
         */
        public MainFrame() {
                initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jTabbedPane1 = new javax.swing.JTabbedPane();
                jPanel2 = new javax.swing.JPanel();
                jScrollPane1 = new javax.swing.JScrollPane();
                jPanel6 = new javax.swing.JPanel();
                jPanel3 = new javax.swing.JPanel();
                jPanel8 = new javax.swing.JPanel();
                jLabel2 = new javax.swing.JLabel();
                jButton7 = new javax.swing.JButton();
                jScrollPane2 = new javax.swing.JScrollPane();
                jPanel9 = new javax.swing.JPanel();
                jPanel12 = new javax.swing.JPanel();
                jSeparator6 = new javax.swing.JSeparator();
                jLabel10 = new javax.swing.JLabel();
                jLabel11 = new javax.swing.JLabel();
                jButton9 = new javax.swing.JButton();
                jPanel13 = new javax.swing.JPanel();
                jSeparator7 = new javax.swing.JSeparator();
                jLabel12 = new javax.swing.JLabel();
                jLabel13 = new javax.swing.JLabel();
                jButton10 = new javax.swing.JButton();
                jPanel14 = new javax.swing.JPanel();
                jSeparator8 = new javax.swing.JSeparator();
                jLabel14 = new javax.swing.JLabel();
                jLabel15 = new javax.swing.JLabel();
                jButton11 = new javax.swing.JButton();
                jPanel15 = new javax.swing.JPanel();
                jSeparator9 = new javax.swing.JSeparator();
                jLabel16 = new javax.swing.JLabel();
                jLabel17 = new javax.swing.JLabel();
                jButton12 = new javax.swing.JButton();
                jPanel4 = new javax.swing.JPanel();
                jPanel16 = new javax.swing.JPanel();
                jSeparator10 = new javax.swing.JSeparator();
                jLabel6 = new javax.swing.JLabel();
                jLabel18 = new javax.swing.JLabel();
                jLabel7 = new javax.swing.JLabel();
                jButton21 = new javax.swing.JButton();
                jPanel17 = new javax.swing.JPanel();
                jSeparator11 = new javax.swing.JSeparator();
                jLabel25 = new javax.swing.JLabel();
                jLabel26 = new javax.swing.JLabel();
                jLabel27 = new javax.swing.JLabel();
                jButton22 = new javax.swing.JButton();
                jPanel18 = new javax.swing.JPanel();
                jSeparator12 = new javax.swing.JSeparator();
                jLabel28 = new javax.swing.JLabel();
                jLabel29 = new javax.swing.JLabel();
                jLabel30 = new javax.swing.JLabel();
                jButton23 = new javax.swing.JButton();
                jButton25 = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle("Order Receiver(GUI Demo)");
                setResizable(false);

                jTabbedPane1.setPreferredSize(new java.awt.Dimension(1000, 700));

                jPanel2.setPreferredSize(new java.awt.Dimension(1000, 700));

                jScrollPane1.setHorizontalScrollBar(null);
                jScrollPane1.getVerticalScrollBar().setUnitIncrement(16);
                jScrollPane1.setPreferredSize(new java.awt.Dimension(1000, 700));

                jPanel6.setPreferredSize(new java.awt.Dimension(1000, 1000));

                //////////////////////////////////////// test /////////////////////////////////
                try (BufferedReader br = new BufferedReader(new FileReader("src\\restaurant_log\\menu_now.txt"))) {
                        String line;
                        while ((line = br.readLine()) != null) {
                                String[] parts = line.split(",");
                                String item_name = parts[0];
                                String item_price = parts[1];
                                String image_Path = parts[2];

                                jPanel6.add(new menu_panel(item_name, item_price, image_Path));
                        }
                } catch (IOException e) {
                        e.printStackTrace();
                        System.out.println("load Menu file eror");
                }

                ////////////////////////////
                /*
                 * for (int i = 0; i < 5; i++) {
                 * menu_panel panel = new menu_panel("mama", "200", "past_not_use");
                 * jPanel6.add(panel);
                 * }
                 */
                jPanel6.setPreferredSize(new java.awt.Dimension(1000, 1000));
                /*
                 * javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
                 * jPanel6.setLayout(jPanel6Layout);
                 * jPanel6Layout.setHorizontalGroup(
                 * jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                 * .addGap(0, 1000, Short.MAX_VALUE));
                 * jPanel6Layout.setVerticalGroup(
                 * jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                 * .addGap(0, 1000, Short.MAX_VALUE));
                 */
                jScrollPane1.setViewportView(jPanel6);

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE));
                jPanel2Layout.setVerticalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE));

                jTabbedPane1.addTab("Menu", jPanel2);

                jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                jLabel2.setText("Total :     12345-.");

                jButton7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                jButton7.setText("Order now");
                jButton7.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton7ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
                jPanel8.setLayout(jPanel8Layout);
                jPanel8Layout.setHorizontalGroup(
                                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel8Layout.createSequentialGroup()
                                                                .addGap(81, 81, 81)
                                                                .addComponent(jLabel2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                400,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(jButton7)
                                                                .addGap(97, 97, 97)));
                jPanel8Layout.setVerticalGroup(
                                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout
                                                                .createSequentialGroup()
                                                                .addContainerGap(24, Short.MAX_VALUE)
                                                                .addGroup(jPanel8Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel2)
                                                                                .addComponent(jButton7))
                                                                .addGap(25, 25, 25)));

                jScrollPane2.setHorizontalScrollBar(null);
                jScrollPane2.getVerticalScrollBar().setUnitIncrement(16);

                jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
                jLabel10.setText("1 x [Menu Name 01]");

                jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                jLabel11.setText("123-.");

                jButton9.setText("-");
                jButton9.setPreferredSize(new java.awt.Dimension(35, 35));
                jButton9.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton9ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
                jPanel12.setLayout(jPanel12Layout);
                jPanel12Layout.setHorizontalGroup(
                                jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jSeparator6)
                                                .addGroup(jPanel12Layout.createSequentialGroup()
                                                                .addGap(27, 27, 27)
                                                                .addComponent(jLabel10)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                544,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(jButton9,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel11)
                                                                .addGap(97, 97, 97)));
                jPanel12Layout.setVerticalGroup(
                                jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout
                                                                .createSequentialGroup()
                                                                .addContainerGap(32, Short.MAX_VALUE)
                                                                .addGroup(jPanel12Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel10)
                                                                                .addComponent(jLabel11)
                                                                                .addComponent(jButton9,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(26, 26, 26)
                                                                .addComponent(jSeparator6,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)));

                jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
                jLabel12.setText("2 x [Menu Name 01]");

                jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                jLabel13.setText("123-.");

                jButton10.setText("-");
                jButton10.setPreferredSize(new java.awt.Dimension(35, 35));
                jButton10.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton10ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
                jPanel13.setLayout(jPanel13Layout);
                jPanel13Layout.setHorizontalGroup(
                                jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jSeparator7)
                                                .addGroup(jPanel13Layout.createSequentialGroup()
                                                                .addGap(27, 27, 27)
                                                                .addComponent(jLabel12)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                544,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(jButton10,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel13)
                                                                .addGap(97, 97, 97)));
                jPanel13Layout.setVerticalGroup(
                                jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout
                                                                .createSequentialGroup()
                                                                .addContainerGap(32, Short.MAX_VALUE)
                                                                .addGroup(jPanel13Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel12)
                                                                                .addComponent(jLabel13)
                                                                                .addComponent(jButton10,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(26, 26, 26)
                                                                .addComponent(jSeparator7,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)));

                jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
                jLabel14.setText("3 x [Menu Name 04]");

                jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                jLabel15.setText("123-.");

                jButton11.setText("-");
                jButton11.setPreferredSize(new java.awt.Dimension(35, 35));
                jButton11.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton11ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
                jPanel14.setLayout(jPanel14Layout);
                jPanel14Layout.setHorizontalGroup(
                                jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jSeparator8)
                                                .addGroup(jPanel14Layout.createSequentialGroup()
                                                                .addGap(27, 27, 27)
                                                                .addComponent(jLabel14)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                544,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(jButton11,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel15)
                                                                .addGap(97, 97, 97)));
                jPanel14Layout.setVerticalGroup(
                                jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout
                                                                .createSequentialGroup()
                                                                .addContainerGap(32, Short.MAX_VALUE)
                                                                .addGroup(jPanel14Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel14)
                                                                                .addComponent(jLabel15)
                                                                                .addComponent(jButton11,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(26, 26, 26)
                                                                .addComponent(jSeparator8,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)));

                jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
                jLabel16.setText("10 x [Menu Name 05]");

                jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                jLabel17.setText("999-.");

                jButton12.setText("-");
                jButton12.setPreferredSize(new java.awt.Dimension(35, 35));
                jButton12.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton12ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
                jPanel15.setLayout(jPanel15Layout);
                jPanel15Layout.setHorizontalGroup(
                                jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jSeparator9)
                                                .addGroup(jPanel15Layout.createSequentialGroup()
                                                                .addGap(27, 27, 27)
                                                                .addComponent(jLabel16)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                530,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(jButton12,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel17)
                                                                .addGap(111, 111, 111)));
                jPanel15Layout.setVerticalGroup(
                                jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout
                                                                .createSequentialGroup()
                                                                .addContainerGap(32, Short.MAX_VALUE)
                                                                .addGroup(jPanel15Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel16)
                                                                                .addComponent(jLabel17)
                                                                                .addComponent(jButton12,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(26, 26, 26)
                                                                .addComponent(jSeparator9,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)));

                javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
                jPanel9.setLayout(jPanel9Layout);
                jPanel9Layout.setHorizontalGroup(
                                jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel9Layout.createSequentialGroup()
                                                                .addGroup(jPanel9Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jPanel12,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jPanel13,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jPanel14,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jPanel15,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(0, 36, Short.MAX_VALUE)));
                jPanel9Layout.setVerticalGroup(
                                jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel9Layout.createSequentialGroup()
                                                                .addComponent(jPanel12,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jPanel13,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jPanel14,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jPanel15,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 145, Short.MAX_VALUE)));

                jScrollPane2.setViewportView(jPanel9);

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1000,
                                                                Short.MAX_VALUE));
                jPanel3Layout.setVerticalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addComponent(jScrollPane2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                565,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jPanel8,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addContainerGap()));

                jTabbedPane1.addTab("Cart", jPanel3);

                jPanel16.setPreferredSize(new java.awt.Dimension(1000, 150));

                jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageFolder/test.jpg"))); // NOI18N

                jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
                jLabel18.setText("[Menu Name 00]");

                jLabel7.setText("Additional Info(if has)");

                jButton21.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                jButton21.setText("remove");
                jButton21.setPreferredSize(new java.awt.Dimension(100, 40));
                jButton21.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton21ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
                jPanel16.setLayout(jPanel16Layout);
                jPanel16Layout.setHorizontalGroup(
                                jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jSeparator10, javax.swing.GroupLayout.DEFAULT_SIZE, 988,
                                                                Short.MAX_VALUE)
                                                .addGroup(jPanel16Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel6)
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel16Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel16Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(jLabel18)
                                                                                                .addGap(64, 651, Short.MAX_VALUE))
                                                                                .addGroup(jPanel16Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(6, 6, 6)
                                                                                                .addComponent(jLabel7)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(jButton21,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                146,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(46, 46, 46)))));
                jPanel16Layout.setVerticalGroup(
                                jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout
                                                                .createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(jPanel16Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel16Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(10, 10, 10)
                                                                                                .addComponent(jLabel18)
                                                                                                .addGroup(jPanel16Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addGroup(jPanel16Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addGap(13, 13, 13)
                                                                                                                                .addComponent(jLabel7))
                                                                                                                .addGroup(jPanel16Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addGap(5, 5, 5)
                                                                                                                                .addComponent(jButton21,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                                .addComponent(jLabel6))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(jSeparator10,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)));

                jPanel17.setPreferredSize(new java.awt.Dimension(1000, 150));

                jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageFolder/test.jpg"))); // NOI18N

                jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
                jLabel26.setText("[Menu Name 01]");

                jLabel27.setText("Additional Info(if has)");

                jButton22.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                jButton22.setText("remove");
                jButton22.setPreferredSize(new java.awt.Dimension(100, 40));
                jButton22.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton22ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
                jPanel17.setLayout(jPanel17Layout);
                jPanel17Layout.setHorizontalGroup(
                                jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jSeparator11, javax.swing.GroupLayout.DEFAULT_SIZE, 988,
                                                                Short.MAX_VALUE)
                                                .addGroup(jPanel17Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel25)
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel17Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel17Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(jLabel26)
                                                                                                .addGap(64, 651, Short.MAX_VALUE))
                                                                                .addGroup(jPanel17Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(6, 6, 6)
                                                                                                .addComponent(jLabel27)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(jButton22,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                146,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(46, 46, 46)))));
                jPanel17Layout.setVerticalGroup(
                                jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel17Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(jPanel17Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel17Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(10, 10, 10)
                                                                                                .addComponent(jLabel26)
                                                                                                .addGroup(jPanel17Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addGroup(jPanel17Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addGap(13, 13, 13)
                                                                                                                                .addComponent(jLabel27))
                                                                                                                .addGroup(jPanel17Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addGap(5, 5, 5)
                                                                                                                                .addComponent(jButton22,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                                .addComponent(jLabel25))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(jSeparator11,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)));

                jPanel18.setPreferredSize(new java.awt.Dimension(1000, 150));

                jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageFolder/test.jpg"))); // NOI18N

                jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
                jLabel29.setText("[Menu Name 02]");

                jLabel30.setText("Additional Info(if has)");

                jButton23.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                jButton23.setText("remove");
                jButton23.setPreferredSize(new java.awt.Dimension(100, 40));
                jButton23.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton23ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
                jPanel18.setLayout(jPanel18Layout);
                jPanel18Layout.setHorizontalGroup(
                                jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jSeparator12, javax.swing.GroupLayout.DEFAULT_SIZE, 988,
                                                                Short.MAX_VALUE)
                                                .addGroup(jPanel18Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel28)
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel18Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel18Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(jLabel29)
                                                                                                .addGap(64, 651, Short.MAX_VALUE))
                                                                                .addGroup(jPanel18Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(6, 6, 6)
                                                                                                .addComponent(jLabel30)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                515,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(jButton23,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                146,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(46, 46, 46)))));
                jPanel18Layout.setVerticalGroup(
                                jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout
                                                                .createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(jPanel18Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel18Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(10, 10, 10)
                                                                                                .addComponent(jLabel29)
                                                                                                .addGroup(jPanel18Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addGroup(jPanel18Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addGap(13, 13, 13)
                                                                                                                                .addComponent(jLabel30))
                                                                                                                .addGroup(jPanel18Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addGap(5, 5, 5)
                                                                                                                                .addComponent(jButton23,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                                .addComponent(jLabel28))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(jSeparator12,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)));

                jButton25.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                jButton25.setText("add");
                jButton25.setPreferredSize(new java.awt.Dimension(100, 40));
                jButton25.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton25ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
                jPanel4.setLayout(jPanel4Layout);
                jPanel4Layout.setHorizontalGroup(
                                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel4Layout.createSequentialGroup()
                                                                .addGroup(jPanel4Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel4Layout
                                                                                                .createSequentialGroup()
                                                                                                .addContainerGap()
                                                                                                .addGroup(jPanel4Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(jPanel16,
                                                                                                                                988,
                                                                                                                                988,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(jPanel17,
                                                                                                                                988,
                                                                                                                                988,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                .addGroup(jPanel4Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(404, 404, 404)
                                                                                                .addComponent(jButton25,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                146,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(jPanel4Layout
                                                                                                .createSequentialGroup()
                                                                                                .addContainerGap()
                                                                                                .addComponent(jPanel18,
                                                                                                                988,
                                                                                                                988,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
                jPanel4Layout.setVerticalGroup(
                                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel4Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jPanel16,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jPanel17,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(23, 23, 23)
                                                                .addComponent(jPanel18,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jButton25,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(122, Short.MAX_VALUE)));

                jTabbedPane1.addTab("Add/Remove", jPanel4);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jTabbedPane1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, Short.MAX_VALUE)));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jTabbedPane1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, Short.MAX_VALUE)));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton7ActionPerformed
                // TODO add your handling code here:
                JOptionPane.showMessageDialog(null,
                                "Your order has been received.\n1 x [Menu Name 00]\n2 x [Menu Name 01]\n3 x [Menu Name 04]\n10 x [Menu Name 05]\nTotal : 12345-.",
                                "Summary", JOptionPane.INFORMATION_MESSAGE);
        }// GEN-LAST:event_jButton7ActionPerformed

        private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton9ActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_jButton9ActionPerformed

        private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton10ActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_jButton10ActionPerformed

        private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton11ActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_jButton11ActionPerformed

        private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton12ActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_jButton12ActionPerformed

        private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton21ActionPerformed
                // TODO add your handling code here:
                JButton source = (JButton) evt.getSource();
                jPanel4.remove(source.getParent());
                jPanel4.revalidate();
                jPanel4.repaint();
        }// GEN-LAST:event_jButton21ActionPerformed

        private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton22ActionPerformed
                // TODO add your handling code here:
                JButton source = (JButton) evt.getSource();
                jPanel4.remove(source.getParent());
                jPanel4.revalidate();
                jPanel4.repaint();
        }// GEN-LAST:event_jButton22ActionPerformed

        private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton23ActionPerformed
                // TODO add your handling code here:
                JButton source = (JButton) evt.getSource();
                jPanel4.remove(source.getParent());
                jPanel4.revalidate();
                jPanel4.repaint();
        }// GEN-LAST:event_jButton23ActionPerformed

        private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton25ActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_jButton25ActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(MainFrame.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(MainFrame.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(MainFrame.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(MainFrame.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                }
                // </editor-fold>

                // Look & Feel
                try {
                        UIManager.setLookAndFeel(new FlatLightLaf());
                        new MainFrame().setVisible(true);
                } catch (UnsupportedLookAndFeelException ex) {
                        System.err.println("Failed to initialize LaF");
                }

                /* Create and display the form */
                // java.awt.EventQueue.invokeLater(new Runnable() {
                // public void run() {
                // new MainFrame().setVisible(true);
                // }
                // });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jButton10;
        private javax.swing.JButton jButton11;
        private javax.swing.JButton jButton12;
        private javax.swing.JButton jButton21;
        private javax.swing.JButton jButton22;
        private javax.swing.JButton jButton23;
        private javax.swing.JButton jButton25;
        private javax.swing.JButton jButton7;
        private javax.swing.JButton jButton9;
        private javax.swing.JLabel jLabel10;
        private javax.swing.JLabel jLabel11;
        private javax.swing.JLabel jLabel12;
        private javax.swing.JLabel jLabel13;
        private javax.swing.JLabel jLabel14;
        private javax.swing.JLabel jLabel15;
        private javax.swing.JLabel jLabel16;
        private javax.swing.JLabel jLabel17;
        private javax.swing.JLabel jLabel18;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel25;
        private javax.swing.JLabel jLabel26;
        private javax.swing.JLabel jLabel27;
        private javax.swing.JLabel jLabel28;
        private javax.swing.JLabel jLabel29;
        private javax.swing.JLabel jLabel30;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JPanel jPanel12;
        private javax.swing.JPanel jPanel13;
        private javax.swing.JPanel jPanel14;
        private javax.swing.JPanel jPanel15;
        private javax.swing.JPanel jPanel16;
        private javax.swing.JPanel jPanel17;
        private javax.swing.JPanel jPanel18;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JPanel jPanel4;
        private javax.swing.JPanel jPanel6;
        private javax.swing.JPanel jPanel8;
        private javax.swing.JPanel jPanel9;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JSeparator jSeparator10;
        private javax.swing.JSeparator jSeparator11;
        private javax.swing.JSeparator jSeparator12;
        private javax.swing.JSeparator jSeparator6;
        private javax.swing.JSeparator jSeparator7;
        private javax.swing.JSeparator jSeparator8;
        private javax.swing.JSeparator jSeparator9;
        private javax.swing.JTabbedPane jTabbedPane1;
        // End of variables declaration//GEN-END:variables
}
