/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package order;

import java.awt.Font;
import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;

import javax.swing.*;

import com.formdev.flatlaf.FlatLightLaf;

import orderreceiverdemo.menu_panel_from;

/**
 *
 * @author meama
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_menu_panel = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        Menu_panel = new javax.swing.JTabbedPane();
        menu_panel1 = new javax.swing.JPanel();
        menu_panel2 = new javax.swing.JPanel();
        menu_panel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        main_menu_panel.setFont(new Font("Tahoma", Font.PLAIN, 12)); // set thai
        Menu_panel.setFont(new Font("Tahoma", Font.PLAIN, 12)); // set thai
        menu_panel1.setFont(new Font("Tahoma", Font.PLAIN, 12)); // set thai
        menu_panel2.setFont(new Font("Tahoma", Font.PLAIN, 12)); // set thai
        menu_panel3.setFont(new Font("Tahoma", Font.PLAIN, 12)); // set thai

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        // javax.swing.GroupLayout menu_panel1Layout = new
        // javax.swing.GroupLayout(menu_panel1);

        //////////////////////////////////////////////////////////////////// add menu
        //////////////////////////////////////////////////////////////////// form file
        //////////////////////////////////////////////////////////////////// //////////////////////
        menu_panel1.setLayout(new BoxLayout(menu_panel1, BoxLayout.Y_AXIS));
        // read menu fry from file
        try (BufferedReader br = new BufferedReader(
                new InputStreamReader(new FileInputStream("src\\restaurant_log\\fry_menu.txt"), "UTF-8"))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] parts = line.split(",");

                if (parts.length >= 3) {
                    String name = parts[0].trim();
                    String price = parts[1].trim();
                    String otherInfo = parts[2].trim();

                    menu_panel1.add(new menu_panel_from(name, price, otherInfo));
                } else {
                    System.out.println("fry_menu format eror: " + line);
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
            System.out.println("Load Menu file error: fry_menu");
        }

        // src\restaurant_log\fry_menu.txt

        /*
         * menu_panel1.setLayout(menu_panel1Layout);
         * menu_panel1Layout.setHorizontalGroup(
         * menu_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.
         * LEADING)
         * .addGap(0, 657, Short.MAX_VALUE));
         * menu_panel1Layout.setVerticalGroup(
         * menu_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.
         * LEADING)
         * .addGap(0, 339, Short.MAX_VALUE));
         */

        Menu_panel.addTab("ต้ม", menu_panel1);

        javax.swing.GroupLayout menu_panel2Layout = new javax.swing.GroupLayout(menu_panel2);
        menu_panel2.setLayout(menu_panel2Layout);
        menu_panel2Layout.setHorizontalGroup(
                menu_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 657, Short.MAX_VALUE));
        menu_panel2Layout.setVerticalGroup(
                menu_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 339, Short.MAX_VALUE));

        Menu_panel.addTab("ผัด", menu_panel2);

        javax.swing.GroupLayout menu_panel3Layout = new javax.swing.GroupLayout(menu_panel3);
        menu_panel3.setLayout(menu_panel3Layout);
        menu_panel3Layout.setHorizontalGroup(
                menu_panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 657, Short.MAX_VALUE));
        menu_panel3Layout.setVerticalGroup(
                menu_panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 339, Short.MAX_VALUE));

        Menu_panel.addTab("ทอด", menu_panel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Menu_panel)
                                .addContainerGap()));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Menu_panel, javax.swing.GroupLayout.Alignment.TRAILING));

        main_menu_panel.addTab("เมนู", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 669, Short.MAX_VALUE));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 374, Short.MAX_VALUE));

        main_menu_panel.addTab("รถเข็น", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 669, Short.MAX_VALUE));
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 374, Short.MAX_VALUE));

        main_menu_panel.addTab("เพิ่ม/ลบ", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 669, Short.MAX_VALUE));
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 374, Short.MAX_VALUE));

        main_menu_panel.addTab("สรุปยอด", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(main_menu_panel));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(main_menu_panel));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
            new main().setVisible(true);
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Menu_panel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane main_menu_panel;
    private javax.swing.JPanel menu_panel1;
    private javax.swing.JPanel menu_panel2;
    private javax.swing.JPanel menu_panel3;
    // End of variables declaration//GEN-END:variables

}
