/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mainframe_material.add.remove;

import javax.swing.*;

import file_loader.write_new_menu;

import java.awt.*;
import java.awt.datatransfer.DataFlavor;
import java.awt.dnd.*;
import java.io.File;
import java.util.List;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;

/**
 *
 * @author meama
 */
public class add_remove_panel extends javax.swing.JPanel {

        /**
         * Creates new form add_remove_panel
         */
        public add_remove_panel() {
                initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        // @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                add_menu_panel = new javax.swing.JPanel();
                jLabel3 = new javax.swing.JLabel();
                panel_label = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                jButton1 = new javax.swing.JButton();
                jTextField1 = new javax.swing.JTextField();
                jTextField2 = new javax.swing.JTextField();
                jLabel7 = new javax.swing.JLabel();
                photo_Panel = new ImagePanel();
                jLabel8 = new javax.swing.JLabel();
                jTextField3 = new javax.swing.JTextField();
                menu_opera_for_add = new javax.swing.JPanel();
                top_panel_opera = new javax.swing.JPanel();
                jLabel2 = new javax.swing.JLabel();
                jScrollPane8 = new javax.swing.JScrollPane();
                photo_Panel7 = new javax.swing.JPanel();

                add_menu_panel.setBackground(new java.awt.Color(255, 255, 255));
                // set defal photo of photo panel
                photo_Panel.setBackgroundImage("src\\ImageFolder\\bgOfaddremove.png");
                // set front
                jTextField1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18));
                jTextField2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18));
                jTextField3.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18));
                jLabel3.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
                jLabel3.setText("ชื่อเมนู");

                panel_label.setFont(new java.awt.Font("Sukhumvit Set", 0, 16));
                panel_label.setText("เพิ่มเมนู");

                jLabel5.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
                jLabel5.setText("ราคา");

                jButton1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
                jButton1.setText("เพิ่ม");
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });

                jTextField1.setText("");

                jTextField2.setText("");

                jLabel7.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
                jLabel7.setText("ประเภทเมนู");

                javax.swing.GroupLayout photo_PanelLayout = new javax.swing.GroupLayout(photo_Panel);
                photo_Panel.setLayout(photo_PanelLayout);
                photo_PanelLayout.setHorizontalGroup(
                                photo_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 345, Short.MAX_VALUE));
                photo_PanelLayout.setVerticalGroup(
                                photo_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 254, Short.MAX_VALUE));

                jLabel8.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
                jLabel8.setText("เลือกรูป");

                jTextField3.setText("");

                javax.swing.GroupLayout add_menu_panelLayout = new javax.swing.GroupLayout(add_menu_panel);
                add_menu_panel.setLayout(add_menu_panelLayout);
                add_menu_panelLayout.setHorizontalGroup(
                                add_menu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(add_menu_panelLayout.createSequentialGroup()
                                                                .addGroup(add_menu_panelLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(add_menu_panelLayout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(168, 168, 168)
                                                                                                .addComponent(jButton1))
                                                                                .addGroup(add_menu_panelLayout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(24, 24, 24)
                                                                                                .addGroup(add_menu_panelLayout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(jLabel8)
                                                                                                                .addGroup(add_menu_panelLayout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                                                false)
                                                                                                                                .addGroup(add_menu_panelLayout
                                                                                                                                                .createSequentialGroup()
                                                                                                                                                .addComponent(jLabel7)
                                                                                                                                                .addPreferredGap(
                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                .addComponent(jTextField3,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                167,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                add_menu_panelLayout
                                                                                                                                                                .createSequentialGroup()
                                                                                                                                                                .addComponent(jLabel3)
                                                                                                                                                                .addPreferredGap(
                                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                                .addComponent(jTextField1,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                167,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                add_menu_panelLayout
                                                                                                                                                                .createSequentialGroup()
                                                                                                                                                                .addComponent(jLabel5)
                                                                                                                                                                .addGap(91, 91, 91)
                                                                                                                                                                .addComponent(jTextField2,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                167,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                                                                .addGroup(add_menu_panelLayout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(60, 60, 60)
                                                                                                .addComponent(photo_Panel,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addContainerGap(73, Short.MAX_VALUE))
                                                .addGroup(add_menu_panelLayout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(add_menu_panelLayout.createSequentialGroup()
                                                                                .addGap(16, 16, 16)
                                                                                .addComponent(panel_label)
                                                                                .addContainerGap(392,
                                                                                                Short.MAX_VALUE))));
                add_menu_panelLayout.setVerticalGroup(
                                add_menu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(add_menu_panelLayout.createSequentialGroup()
                                                                .addGap(67, 67, 67)
                                                                .addGroup(add_menu_panelLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(jTextField1,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel3))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(add_menu_panelLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel5)
                                                                                .addComponent(jTextField2,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(20, 20, 20)
                                                                .addGroup(add_menu_panelLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel7)
                                                                                .addComponent(jTextField3,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel8)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(photo_Panel,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                49,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(jButton1)
                                                                .addGap(28, 28, 28))
                                                .addGroup(add_menu_panelLayout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(add_menu_panelLayout.createSequentialGroup()
                                                                                .addGap(33, 33, 33)
                                                                                .addComponent(panel_label)
                                                                                .addContainerGap(534,
                                                                                                Short.MAX_VALUE))));

                menu_opera_for_add.setBackground(new java.awt.Color(255, 255, 255));

                top_panel_opera.setBackground(new java.awt.Color(255, 255, 255));

                jLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
                jLabel2.setText("จัดการเมนู");

                jScrollPane8.setHorizontalScrollBar(null);

                javax.swing.GroupLayout photo_Panel7Layout = new javax.swing.GroupLayout(photo_Panel7);
                photo_Panel7.setLayout(photo_Panel7Layout);
                photo_Panel7Layout.setHorizontalGroup(
                                photo_Panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 0, Short.MAX_VALUE));
                photo_Panel7Layout.setVerticalGroup(
                                photo_Panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 0, Short.MAX_VALUE));

                jScrollPane8.setViewportView(photo_Panel7);

                javax.swing.GroupLayout top_panel_operaLayout = new javax.swing.GroupLayout(top_panel_opera);
                top_panel_opera.setLayout(top_panel_operaLayout);
                top_panel_operaLayout.setHorizontalGroup(
                                top_panel_operaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(top_panel_operaLayout.createSequentialGroup()
                                                                .addGroup(top_panel_operaLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(top_panel_operaLayout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(14, 14, 14)
                                                                                                .addComponent(jLabel2))
                                                                                .addGroup(top_panel_operaLayout
                                                                                                .createSequentialGroup()
                                                                                                .addContainerGap()
                                                                                                .addComponent(jScrollPane8,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addContainerGap(362, Short.MAX_VALUE)));
                top_panel_operaLayout.setVerticalGroup(
                                top_panel_operaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(top_panel_operaLayout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel2)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jScrollPane8,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));

                javax.swing.GroupLayout menu_opera_for_addLayout = new javax.swing.GroupLayout(menu_opera_for_add);
                menu_opera_for_add.setLayout(menu_opera_for_addLayout);
                menu_opera_for_addLayout.setHorizontalGroup(
                                menu_opera_for_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                menu_opera_for_addLayout.createSequentialGroup()
                                                                                .addComponent(top_panel_opera,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addGap(26, 26, 26)));
                menu_opera_for_addLayout.setVerticalGroup(
                                menu_opera_for_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(menu_opera_for_addLayout.createSequentialGroup()
                                                                .addComponent(top_panel_opera,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                47,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, Short.MAX_VALUE)));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(32, 32, 32)
                                                                .addComponent(add_menu_panel,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(menu_opera_for_add,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(18, Short.MAX_VALUE)));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup()
                                                                .addContainerGap(15, Short.MAX_VALUE)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                false)
                                                                                .addComponent(menu_opera_for_add,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(add_menu_panel,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE))
                                                                .addGap(38, 38, 38)));
                manage_photo(photo_Panel);
        }// </editor-fold>//GEN-END:initComponents
         // manage_photo(photo_Panel); in component when use net bean

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
                // TODO add your handling code here:
                // write file to new to path

                new_menu_name = jTextField1.getText();
                new_mewnu_price = jTextField2.getText();
                new_menu_type = jTextField3.getText();
                System.out.println("name = " + new_menu_name + "price = " + new_mewnu_price);
                if (new_menu_name == "" || new_menu_type == "" || new_mewnu_price == "") {
                        System.out.println("mewnu format add eror");
                } else {
                        Path sourcePath = Paths.get(photo_Panel.get_old_photo_path());
                        Path destinationPath = Paths.get(System.getProperty("user.dir"), "src", "ImageFolder",
                                        photo_Panel.get_new_photo_path());

                        System.out.println("sourcePath = " + sourcePath + "\ndestinationPath" + destinationPath);
                        try {
                                Files.copy(sourcePath, destinationPath, StandardCopyOption.REPLACE_EXISTING);
                                System.out.println("File copied successfully to "
                                                + destinationPath);
                        } catch (IOException e) {
                                System.err.println("Error occurred while copying the file: "
                                                + e.getMessage());
                        }

                        if (file_Write_new_menu.write_menu(new_menu_name, new_mewnu_price, new_menu_type,
                                        photo_Panel.get_new_photo_path())) {
                                reset();
                        }

                }
        }// GEN-LAST:event_jButton1ActionPerformed

        /// define method
        public void reset() {
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField3.setText("");
                try {
                        photo_Panel.setBackgroundImage("src\\ImageFolder\\bgOfaddremove.png");

                } catch (Exception e) {
                        System.out.println("image defal not found");
                }
        }

        public String manage_photo(ImagePanel photo_Panel) {

                // ตั้งค่า DropTarget ให้กับ J
                new DropTarget(photo_Panel, new DropTargetListener() {
                        @Override
                        public void dragEnter(DropTargetDragEvent dtde) {
                        }

                        @Override
                        public void dragOver(DropTargetDragEvent dtde) {
                        }

                        @Override
                        public void dropActionChanged(DropTargetDragEvent dtde) {
                        }

                        @Override
                        public void dragExit(DropTargetEvent dte) {
                        }

                        @Override
                        public void drop(DropTargetDropEvent dtde) {
                                try {

                                        if (dtde.isDataFlavorSupported(DataFlavor.javaFileListFlavor)) {
                                                dtde.acceptDrop(DnDConstants.ACTION_COPY);

                                                // ดึงไฟล์ที่ถูกลากและวาง
                                                List<File> droppedFiles = (List<File>) dtde.getTransferable()
                                                                .getTransferData(DataFlavor.javaFileListFlavor);

                                                File file = droppedFiles.get(0);
                                                String file_path = file.getAbsolutePath();

                                                if (file_path.endsWith(".jpg") || file_path.endsWith(".jpeg")
                                                                || file_path.endsWith(".png")) {

                                                        // file_path

                                                        // String destinationFolderPath =
                                                        // "C:/Users/meama/source/repos/oop_project/src/ImageFolder";
                                                        // String destinationFolderPath = "ImageFolder";

                                                        int lastIndex = file_path.lastIndexOf('\\');
                                                        String temp_path = file_path.substring(lastIndex + 1);
                                                        // temp_path = destinationFolderPath + "/" + temp_path;
                                                        photo_Panel.setnew_photo_path(temp_path);
                                                        photo_Panel.setnew_old_path(file_path);
                                                        System.out.println("new path" + temp_path);

                                                        ImageIcon originalIcon = new ImageIcon(file_path);
                                                        Image image = originalIcon.getImage();
                                                        photo_Panel.setBackgroundImage(file_path);

                                                } else {
                                                        System.out.println("File is not an image");
                                                }

                                        } else {
                                                dtde.rejectDrop();
                                        }
                                } catch (Exception ex) {
                                        ex.printStackTrace();
                                }
                        }
                });

                return "sad";
        }

        private write_new_menu file_Write_new_menu = new write_new_menu();
        private javax.swing.JPanel add_menu_panel;
        private javax.swing.JButton jButton1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private ImagePanel photo_Panel;
        private javax.swing.JPanel photo_Panel7;
        private javax.swing.JScrollPane jScrollPane8;
        private javax.swing.JTextField jTextField1;
        private javax.swing.JTextField jTextField2;
        private javax.swing.JTextField jTextField3;
        private javax.swing.JPanel menu_opera_for_add;
        private javax.swing.JLabel panel_label;
        private javax.swing.JPanel top_panel_opera;
        // for actionlistener
        private String new_menu_name;
        private String new_mewnu_price;
        private String new_menu_type;
        // End of variables declaration//GEN-END:variables

        public class ImagePanel extends JPanel {
                private Image backgroundImage;
                private String new_photo_path = "";
                private String old_path = "";

                protected void paintComponent(Graphics g) {
                        super.paintComponent(g);
                        g.drawImage(backgroundImage, 0, 0, getWidth(), getHeight(), this);
                }

                public void setBackgroundImage(String imagePath) {
                        backgroundImage = new ImageIcon(imagePath).getImage();
                        repaint();
                }

                public void setnew_photo_path(String photo_path) {
                        this.new_photo_path = photo_path;
                }

                public String get_new_photo_path() {
                        return new_photo_path;
                }

                public void setnew_old_path(String photo_path) {
                        this.old_path = photo_path;
                }

                public String get_old_photo_path() {
                        return old_path;
                }
        }

}
