package mainframe_material.add.remove;

/**
 *
 * @author meama
 */
public class remove_sup_panal extends javax.swing.JPanel {

    /**
     * Creates new form remove_sup_panal
     */
    public remove_sup_panal(String menu_name, double menu_price, int menu_status) {
        this.menu_name = menu_name;
        this.menu_price = menu_price;
        this.menu_status = menu_status;
        initComponents(menu_name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents(String menu_name) {

        menu_name_label = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        setBackground(new java.awt.Color(255, 255, 255));

        setPreferredSize(new java.awt.Dimension(436, 100));
        menu_name_label.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18));
        menu_name_label.setText(menu_name);

        jButton2.setText("remove");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(menu_name_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 223,
                                        Short.MAX_VALUE)
                                .addComponent(jButton2)
                                .addGap(59, 59, 59)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(19, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(menu_name_label)
                                        .addComponent(jButton2))
                                .addGap(17, 17, 17)));
    }// </editor-fold>

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    // Variables declaration - do not modify
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel menu_name_label;
    private String menu_name;
    private double menu_price;
    private int menu_status;
    // End of variables declaration
}
