/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mainframe_material.sumary;

import java.awt.Color;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author meama
 */
public class sumary_panel extends javax.swing.JPanel {

        /**
         * Creates new form sumary_panel
         */
        public sumary_panel() {
                initComponents();

        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        // @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jPanel2 = new javax.swing.JPanel();
                jPanel3 = new javax.swing.JPanel();
                jButton1 = new javax.swing.JButton();
                jButton2 = new javax.swing.JButton();
                jButton3 = new javax.swing.JButton();
                jButton4 = new javax.swing.JButton();

                setPreferredSize(new java.awt.Dimension(990, 650));

                jPanel1.setBackground(new java.awt.Color(85, 124, 86));

                jLabel1.setFont(new java.awt.Font("Sukhumvit Set", 0, 60)); // NOI18N
                jLabel1.setText("  สรุปยอดขาย");
                jLabel1.setForeground(Color.white);

                jPanel2.setBackground(new java.awt.Color(165, 182, 141));

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 0, Short.MAX_VALUE));
                jPanel2Layout.setVerticalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 50, Short.MAX_VALUE));

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel1)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE))
                                                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                Short.MAX_VALUE));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel1)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                24,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(jPanel2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)));

                jPanel3.setBackground(new java.awt.Color(252, 250, 238));

                jButton1.setText("สรุปยอดขายรายวัน");
                jButton1.setFont(new java.awt.Font("Sukhumvit Set", 0, 16));
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });

                jButton2.setText("สรุปยอดขายรายสัปดาห์");
                jButton2.setFont(new java.awt.Font("Sukhumvit Set", 0, 16));
                jButton2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton2ActionPerformed(evt);
                        }
                });

                jButton3.setText("สรุปยอดขายรายเดือน");
                jButton3.setFont(new java.awt.Font("Sukhumvit Set", 0, 16));
                jButton3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton3ActionPerformed(evt);
                        }
                });

                jButton4.setText("สรุปยอดขายทั้งหมด");
                jButton4.setFont(new java.awt.Font("Sukhumvit Set", 0, 16));
                jButton4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton4ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addGap(26, 26, 26)
                                                                .addGroup(jPanel3Layout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                false)
                                                                                .addComponent(jButton1,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                150,
                                                                                                Short.MAX_VALUE)
                                                                                .addGroup(jPanel3Layout
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                false)
                                                                                                .addComponent(jButton4,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                150,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(jButton3,
                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(jButton2,
                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)))
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
                jPanel3Layout.setVerticalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jButton1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                38,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jButton2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                38,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jButton3,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                38,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jButton4,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                38,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(282, Short.MAX_VALUE)));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jPanel3,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addContainerGap()));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jPanel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jPanel3,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addContainerGap()));
        }// </editor-fold>

        // day
        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
                LocalDateTime currentTime = LocalDateTime.now();
                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
                DateTimeFormatter formatter2 = DateTimeFormatter.ofPattern("dd-MM-yyyy.HH-mm");
                final String currentDate = currentTime.format(formatter);
                final String fileName = currentTime.format(formatter2);
                System.out.println(currentDate);

                file_loader.excel_write.write_one_day(currentDate);
                JLabel temp = new JLabel("สร้างไฟล์ summary" + fileName + " แล้ว");
                temp.setFont(new java.awt.Font("Sukhumvit Set", 0, 16));
                JOptionPane.showMessageDialog(null, temp, "file created", JOptionPane.INFORMATION_MESSAGE);
                // new File("src/../test.xlsx");
        }

        // week
        private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
                LocalDateTime currentTime = LocalDateTime.now().minusDays(7);
                DateTimeFormatter formatter2 = DateTimeFormatter.ofPattern("dd-MM-yyyy.HH-mm");
                final String fileName = LocalDateTime.now().format(formatter2);

                file_loader.excel_write.write_after(currentTime);
                JLabel temp = new JLabel("สร้างไฟล์ summary" + fileName + " แล้ว");
                temp.setFont(new java.awt.Font("Sukhumvit Set", 0, 16));
                JOptionPane.showMessageDialog(null, temp, "file created", JOptionPane.INFORMATION_MESSAGE);
        }

        // month
        private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
                LocalDateTime currentTime = LocalDateTime.now().minusMonths(1);
                DateTimeFormatter formatter2 = DateTimeFormatter.ofPattern("dd-MM-yyyy.HH-mm");
                final String fileName = LocalDateTime.now().format(formatter2);

                file_loader.excel_write.write_after(currentTime);
                JLabel temp = new JLabel("สร้างไฟล์ summary" + fileName + " แล้ว");
                temp.setFont(new java.awt.Font("Sukhumvit Set", 0, 16));
                JOptionPane.showMessageDialog(null, temp, "file created", JOptionPane.INFORMATION_MESSAGE);
        }

        // year
        private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
                LocalDateTime currentTime = LocalDateTime.now().minusYears(100);
                DateTimeFormatter formatter2 = DateTimeFormatter.ofPattern("dd-MM-yyyy.HH-mm");
                final String fileName = LocalDateTime.now().format(formatter2);

                file_loader.excel_write.write_after(currentTime);
                JLabel temp = new JLabel("สร้างไฟล์ summary" + fileName + " แล้ว");
                temp.setFont(new java.awt.Font("Sukhumvit Set", 0, 16));
                JOptionPane.showMessageDialog(null, temp, "file created", JOptionPane.INFORMATION_MESSAGE);
        }

        // Variables declaration - do not modify
        private javax.swing.JButton jButton1;
        private javax.swing.JButton jButton2;
        private javax.swing.JButton jButton3;
        private javax.swing.JButton jButton4;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        // End of variables declaration
}
